-- MySQL Script generated by MySQL Workbench
-- Fri Jul 29 21:33:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Schema lageo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lageo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lageo` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `lageo` ;

-- -----------------------------------------------------
-- Table `lageo`.`action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lageo`.`action` (
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lageo`.`alteration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lageo`.`alteration` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `assemblage` VARCHAR(255) NULL,
  `alteration_product` INT NULL,
  `con_unit` INT NULL,
  `alteration_type` INT NULL,
  `description` LONGTEXT NULL,
  `ore_deposit_id` INT NOT NULL,
  `ore_id` INT NOT NULL,
  `mine_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_alteration_ore_deposit1_idx` (`ore_deposit_id` ASC) VISIBLE,
  INDEX `fk_alteration_ore1_idx` (`ore_id` ASC) VISIBLE,
  INDEX `fk_alteration_mine1_idx` (`mine_id` ASC) VISIBLE,
  CONSTRAINT `fk_alteration_ore_deposit1`
    FOREIGN KEY (`ore_deposit_id`)
    REFERENCES `lageo`.`ore_deposit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alteration_ore1`
    FOREIGN KEY (`ore_id`)
    REFERENCES `lageo`.`ore` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alteration_mine1`
    FOREIGN KEY (`mine_id`)
    REFERENCES `lageo`.`mine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lageo`.`citation_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lageo`.`citation_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `table_name` VARCHAR(100) NULL,
  `text_content` LONGTEXT NULL,
  `ore_deposit_id` INT NULL,
  `natural_disasters_id` INT NULL,
  `field_area_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_citation_table_ore_deposit1_idx` (`ore_deposit_id` ASC) VISIBLE,
  INDEX `fk_citation_table_natural_disasters????1_idx` (`natural_disasters_id` ASC) VISIBLE,
  INDEX `fk_citation_table_field_area1_idx` (`field_area_id` ASC) VISIBLE,
  CONSTRAINT `fk_citation_table_ore_deposit1`
    FOREIGN KEY (`ore_deposit_id`)
    REFERENCES `lageo`.`ore_deposit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_citation_table_natural_disasters????1`
    FOREIGN KEY (`natural_disasters_id`)
    REFERENCES `lageo`.`natural_disasters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_citation_table_field_area1`
    FOREIGN KEY (`field_area_id`)
    REFERENCES `lageo`.`field_area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lageo`.`domain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lageo`.`domain` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `table_name` VARCHAR(100) NULL,
  `field_name` VARCHAR(100) NULL,
  `group_id` INT NULL,
  `value` VARCHAR(255) NULL,
  `fa_value` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lageo`.`environmental_issue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lageo`.`environmental_issue` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `AMD` BIT NULL,
  `air_polution` FLOAT NULL,
  `water_polution` FLOAT NULL,
  `soil_polution` FLOAT NULL,
  `env_minerals` TEXT NULL,
  `description` TEXT NULL,
  `ore_deposit_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_environmental_issue_ore_deposit1_idx` (`ore_deposit_id` ASC) VISIBLE,
  CONSTRAINT `fk_environmental_issue_ore_deposit1`
    FOREIGN KEY (`ore_deposit_id`)
    REFERENCES `lageo`.`ore_deposit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lageo`.`fault`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lageo`.`fault` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mechanism` INT NULL,
  `length` BIGINT NULL,
  `dip_direction` DOUBLE NULL,
  `text_content` LONGTEXT NULL,
  `geologic_structure_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fault_geologic_structure1_idx` (`geologic_structure_id` ASC) VISIBLE,
  CONSTRAINT `fk_fault_geologic_structure1`
    FOREIGN KEY (`geologic_structure_id`)
    REFERENCES `lageo`.`geologic_structure` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lageo`.`field_area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lageo`.`field_area` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` INT NULL,
  `name` VARCHAR(100) NULL,
  `svg_code` LONGTEXT NOT NULL,
  `area` DOUBLE NULL,
  `age_range` VARCHAR(50) NULL,
  `description` LONGTEXT NULL,
  `geo_location_id` INT NOT NULL,
  `map_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_field_area_geo_location1_idx` (`geo_location_id` ASC) VISIBLE,
  INDEX `fk_field_area_map_unit_definition1_idx` (`map_id` ASC) VISIBLE,
  CONSTRAINT `fk_field_area_geo_location1`
    FOREIGN KEY (`geo_location_id`)
    REFERENCES `lageo`.`geo_location !!!!!` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_field_area_map_unit_definition1`
    FOREIGN KEY (`map_id`)
    REFERENCES `lageo`.`map_unit_definition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lageo`.`fold`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lageo`.`fold` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_id` INT NULL,
  `text_content` LONGTEXT NULL,
  `geologic_structure_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fold_geologic_structure1_idx` (`geologic_structure_id` ASC) VISIBLE,
  CONSTRAINT `fk_fold_geologic_structure1`
    FOREIGN KEY (`geologic_structure_id`)
    REFERENCES `lageo`.`geologic_structure` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lageo`.`form_litho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lageo`.`form_litho` (
  `lithology_id` INT NOT NULL,
  `formation_id` INT NOT NULL,
  INDEX `fk_form_litho_lithology1_idx` (`lithology_id` ASC) VISIBLE,
  INDEX `fk_form_litho_formation1_idx` (`formation_id` ASC) VISIBLE,
  PRIMARY KEY (`lithology_id`, `formation_id`),
  CONSTRAINT `fk_form_litho_lithology1`
    FOREIGN KEY (`lithology_id`)
    REFERENCES `lageo`.`lithology` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_form_litho_formation1`
    FOREIGN KEY (`formation_id`)
    REFERENCES `lageo`.`formation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lageo`.`formation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lageo`.`formation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  `map_unit_id` INT NULL,
  `text_content` LONGTEXT NULL,
  `citation_table_id` INT NOT NULL,
  `field_area_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_formation_citation_table1_idx` (`citation_table_id` ASC) VISIBLE,
  INDEX `fk_formation_field_area1_idx` (`field_area_id` ASC) VISIBLE,
  CONSTRAINT `fk_formation_citation_table1`
    FOREIGN KEY (`citation_table_id`)
    REFERENCES `lageo`.`citation_table` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_formation_field_area1`
    FOREIGN KEY (`field_area_id`)
    REFERENCES `lageo`.`field_area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lageo`.`fracture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lageo`.`fracture` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `length` BIGINT NULL,
  `dip_direction` DOUBLE NULL,
  `text_content` LONGTEXT NULL,
  `geologic_structure_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fracture_geologic_structure1_idx` (`geologic_structure_id` ASC) VISIBLE,
  CONSTRAINT `fk_fracture_geologic_structure1`
    FOREIGN KEY (`geologic_structure_id`)
    REFERENCES `lageo`.`geologic_structure` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lageo`.`geo_location !!!!!`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lageo`.`geo_location !!!!!` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `latitude` VARCHAR(45) NULL,
  `longitude` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `path_stroke_size` INT NULL,
  `x1_y1` INT NULL,
  `x2_y2` INT NULL,
  `r` INT NULL,
  `scale` FLOAT NULL,
  `first_vector` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lageo`.`geo_sample`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lageo`.`geo_sample` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `field_station` INT NULL,
  `material` INT NULL,
  `method` INT NULL,
  `coordinate_x` INT NULL,
  `coordinate_y` INT NULL,
  `citation_id` INT NULL,
  `description` TEXT NULL,
  `field_area_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_geo_sample  ????_field_area1_idx` (`field_area_id` ASC) VISIBLE,
  CONSTRAINT `fk_geo_sample  ????_field_area1`
    FOREIGN KEY (`field_area_id`)
    REFERENCES `lageo`.`field_area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'آیا رابطه با فیلد_اریا یک به یک است؟';


-- -----------------------------------------------------
-- Table `lageo`.`geochemistery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lageo`.`geochemistery` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `element_name` VARCHAR(255) NULL,
  `concentration` FLOAT NULL,
  `con_unit` INT NULL,
  `ore_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_geochemistery_ore1_idx` (`ore_id` ASC) VISIBLE,
  CONSTRAINT `fk_geochemistery_ore1`
    FOREIGN KEY (`ore_id`)
    REFERENCES `lageo`.`ore` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lageo`.`geologic_structure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lageo`.`geologic_structure` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `type` VARCHAR(255) NULL,
  `text_content` LONGTEXT NULL,
  `field_area_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_geologic_structure_field_area1_idx` (`field_area_id` ASC) VISIBLE,
  CONSTRAINT `fk_geologic_structure_field_area1`
    FOREIGN KEY (`field_area_id`)
    REFERENCES `lageo`.`field_area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'ایا رابطه با فیلد_اریا یک به یک است؟';


-- -----------------------------------------------------
-- Table `lageo`.`geologic_zone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lageo`.`geologic_zone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `text_content` LONGTEXT NULL,
  `description` LONGTEXT NULL,
  `citation` TEXT NULL,
  `parent_zone_id` INT NULL,
  `field_area_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_geologic_zone_geologic_zone1_idx` (`parent_zone_id` ASC) VISIBLE,
  INDEX `fk_geologic_zone_field_area1_idx` (`field_area_id` ASC) VISIBLE,
  CONSTRAINT `fk_geologic_zone_geologic_zone1`
    FOREIGN KEY (`parent_zone_id`)
    REFERENCES `lageo`.`geologic_zone` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_geologic_zone_field_area1`
    FOREIGN KEY (`field_area_id`)
    REFERENCES `lageo`.`field_area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lageo`.`lithology`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lageo`.`lithology` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `map_unit_id` INT NULL,
  `parent_lithology_id` INT NULL,
  `text_content` LONGTEXT NULL,
  `formation_id` INT NULL,
  `age_range` VARCHAR(255) NULL,
  `citation_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lithology_lithology1_idx` (`parent_lithology_id` ASC) VISIBLE,
  INDEX `fk_lithology_citation_table1_idx` (`citation_id` ASC) VISIBLE,
  CONSTRAINT `fk_lithology_lithology1`
    FOREIGN KEY (`parent_lithology_id`)
    REFERENCES `lageo`.`lithology` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lithology_citation_table1`
    FOREIGN KEY (`citation_id`)
    REFERENCES `lageo`.`citation_table` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lageo`.`map_unit_definition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lageo`.`map_unit_definition` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `type` VARCHAR(100) NULL,
  `scale` INT NULL,
  `GIS_dataset` INT NULL,
  `locality` LONGTEXT NULL,
  `unit_rock` VARCHAR(45) NULL,
  `thickness_range` VARCHAR(100) NULL,
  `age_range` VARCHAR(100) NULL,
  `parent_map_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_map_unit_definition_map_unit_definition1_idx` (`parent_map_id` ASC) VISIBLE,
  CONSTRAINT `fk_map_unit_definition_map_unit_definition1`
    FOREIGN KEY (`parent_map_id`)
    REFERENCES `lageo`.`map_unit_definition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lageo`.`mine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lageo`.`mine` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `age_range` VARCHAR(100) NULL,
  `host_rock` VARCHAR(100) NULL,
  `is_active` BIT NULL,
  `is_abandoned` BIT NULL,
  `mining_type` INT NULL,
  `definite_reserve` VARCHAR(45) NULL,
  `probable_reserve` VARCHAR(45) NULL,
  `possible_reserve` VARCHAR(45) NULL,
  `commodity_type` INT NULL,
  `ore_deposit_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mine_ore_deposit1_idx` (`ore_deposit_id` ASC) VISIBLE,
  CONSTRAINT `fk_mine_ore_deposit1`
    FOREIGN KEY (`ore_deposit_id`)
    REFERENCES `lageo`.`ore_deposit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lageo`.`natural_disasters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lageo`.`natural_disasters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `date` DATETIME NULL,
  `intensity` VARCHAR(100) NULL,
  `type` VARCHAR(45) NULL,
  `citation_id` INT NULL,
  `text_content` TEXT NULL,
  `field_area_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_natural_disasters_field_area1_idx` (`field_area_id` ASC) VISIBLE,
  CONSTRAINT `fk_natural_disasters_field_area1`
    FOREIGN KEY (`field_area_id`)
    REFERENCES `lageo`.`field_area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lageo`.`ore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lageo`.`ore` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` INT NULL,
  `grade` FLOAT NULL,
  `texture` INT NULL,
  `structure` INT NULL,
  `gangue` INT NULL,
  `tonage` FLOAT NULL,
  `description` LONGTEXT NULL,
  `mine_id` INT NOT NULL,
  `ore_deposit_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ore_mine1_idx` (`mine_id` ASC) VISIBLE,
  INDEX `fk_ore_ore_deposit1_idx` (`ore_deposit_id` ASC) VISIBLE,
  CONSTRAINT `fk_ore_mine1`
    FOREIGN KEY (`mine_id`)
    REFERENCES `lageo`.`mine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ore_ore_deposit1`
    FOREIGN KEY (`ore_deposit_id`)
    REFERENCES `lageo`.`ore_deposit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lageo`.`ore_deposit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lageo`.`ore_deposit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `mineralization_type` INT NULL,
  `ore_mineralogy` LONGTEXT NULL,
  `geomorphology` INT NULL,
  `host_rocks` INT NULL,
  `age_range` VARCHAR(100) NULL,
  `description` LONGTEXT NULL,
  `field_area_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ore_deposit_field_area1_idx` (`field_area_id` ASC) VISIBLE,
  CONSTRAINT `fk_ore_deposit_field_area1`
    FOREIGN KEY (`field_area_id`)
    REFERENCES `lageo`.`field_area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lageo`.`ore_mineral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lageo`.`ore_mineral` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `age_range` VARCHAR(255) NULL,
  `type` INT NULL,
  `frequency` FLOAT NULL,
  `importance` BIT NULL,
  `alteration_products` INT NULL,
  `description` LONGTEXT NULL,
  `ore_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ore_mineral_ore1_idx` (`ore_id` ASC) VISIBLE,
  CONSTRAINT `fk_ore_mineral_ore1`
    FOREIGN KEY (`ore_id`)
    REFERENCES `lageo`.`ore` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lageo`.`publication_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lageo`.`publication_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `field_area_id` INT NOT NULL,
  `text_content` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_publication_info_field_area1_idx` (`field_area_id` ASC) VISIBLE,
  CONSTRAINT `fk_publication_info_field_area1`
    FOREIGN KEY (`field_area_id`)
    REFERENCES `lageo`.`field_area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lageo`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lageo`.`role` (
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lageo`.`role_access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lageo`.`role_access` (
  `action_name` VARCHAR(100) NOT NULL,
  `role_name` VARCHAR(50) NOT NULL,
  `access_type` BIT NULL,
  INDEX `fk_role_access_role1_idx` (`role_name` ASC) VISIBLE,
  PRIMARY KEY (`action_name`, `role_name`),
  CONSTRAINT `fk_role_access_role1`
    FOREIGN KEY (`role_name`)
    REFERENCES `lageo`.`role` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_access_action1`
    FOREIGN KEY (`action_name`)
    REFERENCES `lageo`.`action` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lageo`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lageo`.`user` (
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `fullname` VARCHAR(100) NULL DEFAULT NULL,
  `ssn` BIGINT NULL DEFAULT NULL,
  `contact` BIGINT NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lageo`.`user_in_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lageo`.`user_in_role` (
  `role_name` VARCHAR(50) NOT NULL,
  `user_username` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`role_name`, `user_username`),
  INDEX `fk_user_in_role_role1_idx` (`role_name` ASC) VISIBLE,
  INDEX `fk_user_in_role_user1_idx` (`user_username` ASC) VISIBLE,
  CONSTRAINT `fk_user_in_role_role1`
    FOREIGN KEY (`role_name`)
    REFERENCES `lageo`.`role` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_in_role_user1`
    FOREIGN KEY (`user_username`)
    REFERENCES `lageo`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
